# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: kittens.proto for package 'bmigo.micro'

require 'grpc'
require 'kittens_pb'

module Bmigo
  module Micro
    module Kittens
      class Service

        include GRPC::GenericService

        self.marshal_class_method = :encode
        self.unmarshal_class_method = :decode
        self.service_name = 'bmigo.micro.Kittens'

        rpc :List, Request, Response
      end

      Stub = Service.rpc_stub_class
    end
  end
end
