# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: kittens.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "bmigo.grpc.Request" do
    optional :name, :string, 1
  end
  add_message "bmigo.grpc.Response" do
    optional :msg, :string, 1
  end
end

module Bmigo
  module Grpc
    Request = Google::Protobuf::DescriptorPool.generated_pool.lookup("bmigo.grpc.Request").msgclass
    Response = Google::Protobuf::DescriptorPool.generated_pool.lookup("bmigo.grpc.Response").msgclass
  end
end
